language: node_js
node_js:
  - stable

install:
  - npm install
script:
  - npm test
  - npm build

before_deploy:
  - cd ./dist
deploy:
  skip_cleanup: true
  provider: heroku
  app: travis-ci-test-2019
  on:
    repo: koskh/ci-cl
    branch: master
  api_key:
    secure: E5+GI2Mlh+A8C88JUhDqbknJDYmtUqt2IK+YrpYbZB0kRQn2m3mEdGhYPFb6wpW9kXSOIllQMmC7QJqbRUSx53MB6ey6TNdDe7r/vmshyuV6du7MrFg0tdXWWEmevGQ/jCVyZ46hCt4/rZ2okF9XnKYR4lzM238hEV9jbEE7D6TmHVFBn1zYmzNmjrvWgU7uFwWbXwO8PsXHGE6wlsuRMOHBIEhjGLpLnlIuOid0QPmbjbKk9UNK07hqnAEI5UwR8jXCctVDur2AbQLBLlR9qgWCukPkUknr4Lcdond3B7ZRArBCVb886UxznI35vXOustCAjWIKqdJ9s0IMrolgoPZ/TxeCEWQJJ2fy1GiS3z+1cSccnYLTTr6iqDe6K7lQys/1n94kuFokcysbBxnML3N54aNMDHABgxWFn/ZrEmezZmeyJ8yRLMAo4srBXHkumS++Tr+ONRLOExTjbk5U8m7KcxhCN2ciPx/5nYUy7EOfB3eLkbbFU8qSAckZJRCB+53440E4AUowVvD/Lxq6QXalCZEiSibKoDm/Ct7bEjfC5lN4CZ+VMUfKA+ScAlHi7vNg2bw3L7Ci+M0Uxgb/KH0+ASh5QW0sCoy4CmvyCDRJH1oW+w3rx1e2dXqqIe29wvj1OKhgVXdC05L6dkDlMlp1cu3VKIYVrFvvTVh3ih8=
