language: node_js
node_js:
  - stable
install:
  - npm install
script:
  - npm test

deploy:
  provider: heroku
  api_key:
    secure: "Qlh+GTLYJJDOwNsCNzTom/8dPGoQOxm6PYl/nvwaOnBCtVDl199BuGSqH00qHCyB97ENZ7owOEqU5ALgNAG0cnqEPuhsh1jhScqHR4tF1Nb+PXemM61aTUeQLhlq1ET/GPckn59xqpDlxFbZJQ61wRO20R2X3qiJwqY6DPnbUrqMMVNsebGn1dlsDweYN3XgNgd+Bdt9zXtvMGgtjQMubDoAAWTzBtFOvkSk6z7CFz9rQHLlIfz+qiDy6+ySp0qqtm1MvEUL1Rb7+wKGV2qyRqEUg1BxLiOQy3hBskyLTeJcG0d9gn+L0RueW/UX4YTSTHATb6NwVQlYHr69La3/eMr9oQcN3D6T9aPORluk70WYQfTno8wZm9AsA13C+87/nZHFagI3r9y9aBa3EPSmHOqP3grOwczzs1ePXhkKR+p31Jb0fprTQfXDERfKLT3LkK2fCqbCc2x4dvFov3Gw2jn0So88/uZSz0sVFKrWZnqoD+4qD0+Ft/3vtQI/IPQhK6nzYzdPf8KilR/cI/0JJF1YYVy0OUI3gJw2CHNN31D+4s5cAbv0PJRiuJhH1ptPbC76V9AeZ+j9tjoN57AJvX0h1Qu1Yzuxr9b5Wl5uruNmiyROfvt1AStqCmYOZVBrprRFic+QTMJ3xBMSDBe9jsfI19MtFWr/HQ93Afu9+JA="
    master: travis-ci-test-2019