language: node_js
node_js:
  - stable

install:
  - npm install
script:
  - npm test

before_deploy:
  - cd ./dist
deploy:
  provider: heroku
  app: travis-ci-test-2019
  on:
    repo: koskh/ci-cl
    branch: master
  api_key:
      secure: j67YolIuzqVCe3ZZNA2iSNUjLUgrn6t9yW8RjC1KmpP6nV1qIgpHJCMAAeyYYW5699dpoWGu82dGzW1Cz4AejmyxZ8ukgj5TmG3ksRSjElb1LVOI7VkfT3pOkJwVfIzduj+PPTH84Gt9XUcfnZlMrqwaN9a0G+FD12MfB1tAFfZwKkIyFRNxPsvXlCIZQUOuBxpJ5vNQfP8IE2sODYfHEIEAgfeY1bUE4lZspl7fj+9XYxa8j9oiDq30qDGS1zBSb1sDFQPwxW9YpUYDo80nE7wTyJb1QermvIcWifngR4H6iz9tVAb/OJQ+gS4j2NWcHJnGyUTCP5GY7fgPnZhFkZ9fgGHFsCeSeWjuO3lJiJDpbmGKbe2H3Ikl1giOtD6xlTSbBJWO16u5gmBgVGi+YLNGP0tGNDaML2gFma4WqPChqzCiDJRyzxZLCn6hCVKBNLLKV2zGGqXKqaHGwhJ2ORkx8c2VjfslWsgn41zB7LVSXnKlb9gS/0NSt3fBn67v+h0+ixmZrofk2xyuM4YbWs11bVirs1lXvk0X/MRyu/r4Q04h9nIskEXlxQVAE+todhZtmWwXXJ2L4t6GhQdFAJh9b/GTUYP59Nv5Q0O60EFmSlGbM12nzqMiDuo7O4/noDT7bp1Zzad/68O0K7PIylGpsEQLwH14EvDeEBGqR3Y=
